cluster : prod

namelists:
  nodes: &all-nodes "pr[1-288],prod-login[1-3],pross[1-4],prmds[1-2],prldms1"
  ib-nodes: &all-hosts "pr[1-288]-ib0,prod-login[1-3]-ib0,pross[1-4]-ib0,prmds[1-2]-ib0,prldms1-ib0"
  rdma-nodes: &all-rdma "pr[1-288]/rdma,prod-login[1-3]/rdma,pross[1-4]/rdma,prmds[1-2]/rdma,prldms1/rdma"
  sock-nodes: &all-sock "pr[1-288]/sock,prod-login[1-3]/sock,pross[1-4]/sock,prmds[1-2]/sock,prldms1/sock"

daemons:
  - names : *all-nodes 
    hosts : *all-hosts
    endpoints :
      - names : *all-rdma
        ports : &rdma-port "411"
        maestro_comm : False
        xprt : rdma
        auth :
          name : ovis
          conf : /etc/sysconfig/ldms.d/ClusterSecrets/ldmsauth.conf

      - names : *all-sock
        ports : &sock-port "412"
        maestro_comm : False
        xprt : sock
        auth :
          name : munge

  - names : &agg-name L1d-agg
    hosts : prldms1
    endpoints :
      - names : prldms1-agg
        ports : "413"
        maestro_comm : False
        xprt : sock
        auth :
          name : ovis
          conf : /etc/sysconfig/ldms.d/ClusterSecrets/ldmsauth.conf

aggregators:
  - daemons : *agg-name
# stuff not handled correctly in maestro yet
    file : L1-agg
    epilog : |
      prdcr_subscribe regex=.* stream=kokkos-perf-data-ep
      prdcr_subscribe regex=.* stream=kokkos-scivar-data
      prdcr_subscribe regex=.* stream=kokkos-scivar-meta
      prdcr_subscribe regex=.* stream=darshanConnector
      prdcr_subscribe regex=.* stream=slurm
    peers : 
      - daemons   : *all-nodes
        endpoints : *all-rdma
        reconnect : 20s
        type      : active
        subscribe :
          - stream : 'kokkos-perf-data'
            regex : .*
          - stream : 'caliper-perf-data'
            regex : .*
          - stream : 'kokkos-scivar-data'
            regex : .*
          - stream : 'kokkos-scivar-meta'
            regex : .*
          - stream : 'darshanConnector'
            regex : .*
          - stream : 'slurm'
            regex : .*
        updaters  :
          - mode     : pull
            interval : "1.0s"
            offset   : "100ms"
            sets     :
              - regex : .*
                field : inst

sampler_time_defaults : &sampler-time-defaults
  interval : "1s"
  offset : "0s"

sampler_config_defaults : &sampler-config-defaults
  job_set : ${host}/jobid
  component_id: ${COMPONENT_ID}
  schema : ~{name}
  instance : ${host}/~{schema}
  job_set : ${host}/jobid
  perm : "0644"

samplers:
  - daemons : *agg-name
    file : L1-samplers
    prolog : |
      metric_sets_default_authz perm=0644
    plugins :
      - <<: *sampler-time-defaults
        name : dstat
        config :
          <<: *sampler-config-defaults
          io : 1
          stat : 1
          statm : 1
          fdtypes : 1
          auto-schema : 1
      - <<: *sampler-time-defaults
        name : meminfo
        config :
          <<: *sampler-config-defaults
          schema : meminfo_l1

  - daemons : *all-nodes
    file : L0-samplers
    prolog : |
      metric_sets_default_authz perm=0644
    epilog : |
      auth_add name=munge plugin=munge
      listen port=412 xprt=sock auth=munge
    plugins :
      - <<: *sampler-time-defaults
        name : jobid
        config :
          <<: *sampler-config-defaults
          file : /var/run/ldms.slurm.jobinfo
      - <<: *sampler-time-defaults
        name : lustre_client
        config :
          <<: *sampler-config-defaults
      - <<: *sampler-time-defaults
        name : loadavg
        config :
          <<: *sampler-config-defaults
      - <<: *sampler-time-defaults
        name : tx2mon
        config :
          <<: *sampler-config-defaults
      - <<: *sampler-time-defaults
        name : meminfo
        config :
          <<: *sampler-config-defaults
      - <<: *sampler-time-defaults
        name : lnet_stats
        config :
          <<: *sampler-config-defaults
      - <<: *sampler-time-defaults
        name : vmstat
        config :
          <<: *sampler-config-defaults
      - <<: *sampler-time-defaults
        name : procnfs
        config :
          <<: *sampler-config-defaults
      - <<: *sampler-time-defaults
        name : procstat
        config :
          <<: *sampler-config-defaults
          maxcpu : 0
          schema : procstat_0
      - <<: *sampler-time-defaults
        name : procnet
        config :
          <<: *sampler-config-defaults
      - <<: *sampler-time-defaults
        name : sysclassib
        config :
          <<: *sampler-config-defaults
          ports : "mlx5_0.1,mlx5_1.1"
          schema : sysclassib_lserver
      - <<: *sampler-time-defaults
        name : dstat
        config :
          <<: *sampler-config-defaults
          io : 1
          stat : 1
          statm : 1
          fdtypes : 1
          auto-schema : 1


store_config_defaults: &csv-defaults
  name : csv-~{schema}
  daemons : *agg-name
  container : store_csv
  plugin :
    name : store_csv
    config :
      path : /ldmslocal/store
      altheader : 0
      typeheader : 1
      create_uid : 3031
      create_gid : 3031

stores:
  - <<: *csv-defaults
    schema : jobid
  - <<: *csv-defaults
    schema : lustre_client
  - <<: *csv-defaults
    schema : loadavg
  - <<: *csv-defaults
    schema : tx2mon
  - <<: *csv-defaults
    schema : meminfo
  - <<: *csv-defaults
    schema : lnet_stats
  - <<: *csv-defaults
    schema : vmstat
  - <<: *csv-defaults
    schema : procnfs
  - <<: *csv-defaults
    schema : procstat
  - <<: *csv-defaults
    schema : procnet
  - <<: *csv-defaults
    schema : sysclassib

  - <<: *csv-defaults
    schema : meminfo_l1
    metrics:
      - Active
      - MemFree

  - <<: *csv-defaults
    schema : dstat_37
    producers:
      - regex : "pr1.*"
      - regex : "pr2.*"
